// REAL BUSTLER BUG DATA
// Source: Bustler internal bug report sheet
// Columns: date, platform, device, bug, attachment, reportedBy, status, priority, resolvedOrNot

export const bustlerRawTickets = [
  {
    date: "14/05/2026",
    platform: "Both",
    device: "iOS",
    bug: "Crashed after selecting any option from + menu",
    attachment: "File",
    reportedBy: "Kannanunni",
    status: "Completed",
    priority: "P1",
    resolvedOrNot: "Not",
  },
  {
    date: "15/05/2026",
    platform: "Bustler",
    device: "Android",
    bug: "When refreshing the My Bustles page it is popping out the order details page",
    attachment: "File",
    reportedBy: "Navaneeth",
    status: "Completed",
    priority: "P1",
    resolvedOrNot: "Not",
  },
  {
    date: "08/05/2026",
    platform: "Seeker",
    device: "Both",
    bug: "When a time slot is booked and accepted by the Bustler, it is not removed from the available time slots",
    attachment: "File",
    reportedBy: "Vivek",
    status: "Completed",
    priority: "P1",
    resolvedOrNot: "Resolved",
  },
  {
    date: "09/05/2026",
    platform: "Seeker",
    device: "Both",
    bug: "Unable to make payment here",
    attachment: "File",
    reportedBy: "Vivek",
    status: "Hold",
    priority: "P1",
    resolvedOrNot: "Not",
  },
  {
    date: "15/05/2026",
    platform: "Seeker",
    device: "Android",
    bug: "An advance payment was made for a Bustler, but the app closed suddenly during the payment process. A confirmation email was received stating the payment was successful, but when reopening the app, it still asks to make the advance payment again.",
    attachment: "File",
    reportedBy: "Vivek",
    status: "Open",
    priority: "P1",
    resolvedOrNot: "Not",
  },
  {
    date: "08/05/2026",
    platform: "Both",
    device: "Both",
    bug: "Message notifications are not working",
    attachment: "File",
    reportedBy: "Vivek",
    status: "Open",
    priority: "P2",
    resolvedOrNot: "Not",
  },
  {
    date: "21/05/2026",
    platform: "Seeker",
    device: "Android",
    bug: "When we create a Bustle with a certain category and it gets verified, editing the job category later does not send it for review again",
    attachment: "File",
    reportedBy: "Vivek",
    status: "Open",
    priority: "P2",
    resolvedOrNot: "Not",
  },
  {
    date: "13/05/2026",
    platform: "Login Page",
    device: "Both",
    bug: "When entering a one-letter last name during sign-up, it shows the message: Last name can only contain letters, spaces, and dots",
    attachment: "File",
    reportedBy: "Vivek",
    status: "Completed",
    priority: "P1",
    resolvedOrNot: "Resolved",
  },
  {
    date: "15/05/2026",
    platform: "Seeker",
    device: "Android",
    bug: "After adding favourite categories, it is not updating. It is updating only after closing the app",
    attachment: "File",
    reportedBy: "Navaneeth",
    status: "Completed",
    priority: "P2",
    resolvedOrNot: "Resolved",
  },
];